version: "3"
services:
  dns-warrior:
    build: .
    container_name: warrior
    image: dns-warrior:1.0
    networks:
      - warrior
    ports:
      - "53:53/udp"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - warrior
    ports:
      - "27017:27017"
networks:
  warrior:
    driver: bridge